services:
  backend:
    build:
      context: backend
    env_file:
      - "prod.env"
    restart: always
    ports:
      - 8000:8000

  frontend:
    build:
      context: frontend
    restart: always
    depends_on:
      - backend
    ports:
      - 80:80
